POST http://localhost:5015/V5/GpsTable/Insert/InsertWithColumns
Content-Type: application/json

{
	"Longitude" : "",
	"Latitude" : "",
	"TreeName" : "",
	"DateTime" : ""
	"Longitude" : "",
	"Latitude" : "",
	"TreeName" : "",
	"DateTime" : ""
}