POST http://localhost:5015/V14/GpsTable/SubTable/Insert/WithUuIdAndDT/{RowIndex}/{KeyName}
Content-Type: application/json

{
  "DateTime": "",
  "TreeName": "",
  "Latitude": "",
  "Longitude": "",
  "UserName": "",
  "pk": ""
}