POST http://localhost:5015/SV6/GpsTable/SubTable/Alter/WithPk/{RowPk}/{KeyName}/{pk}
Content-Type: application/json

{
  "DateTime": "",
  "TreeName": "",
  "Latitude": "",
  "Longitude": "",
  "UserName": "",
  "pk": ""
}