POST http://localhost:5015/V16/Certificates/Insert/AsIsAndTS
Content-Type: application/json

{
  "username": "",
  "password": "",
  "name": "",
  "date": "",
  "plantNo": "",
  "lat": "",
  "lng": ""
}
