POST http://localhost:3000/SV2/GpsTable/Alter/ColumnsWithPk/{pk}
Content-Type: application/json

{
  "DateTime": "",
  "TreeName": "",
  "Latitude": "",
  "Longitude": "",
  "UserName": "",
  "pk": ""
}