POST http://localhost:5015/SV7/GpsTable/Insert/BulkAsIs
Content-Type: application/json

[
  {
    "DateTime": "",
    "TreeName": "",
    "Latitude": "",
    "Longitude": "",
    "UserName": "",
    "pk": ""
  }
]