POST http://localhost:5015/V13/GpsTable/Insert/SchemaColumnsOnly
Content-Type: application/json

{
  "DateTime": "",
  "TreeName": "",
  "Latitude": "",
  "Longitude": "",
  "UserName": "",
  "pk": ""
}