POST http://localhost:5015/V13/GpsTable/Alter/ColumnsWithPk/{pk}
Content-Type: application/json

{
  "DateTime": "",
  "TreeName": "",
  "Latitude": "",
  "Longitude": "",
  "UserName": "",
  "pk": ""
}